[package]
name = "redscript-decompiler"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
redscript = { path = "../core" }
log.workspace = true
thiserror.workspace = true
hashbrown.workspace = true
itertools.workspace = true
