[package]
name = "redscript-decompiler"
version = "0.3.0-RC1"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
redscript = { path = "../core" }
log = "0.4"

[package.metadata.release]
disable-tag = true
