[package]
name = "redscript-decompiler"
version = "0.2.3-dev"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
redscript = { path = "../core" }
log = "0.4"
