[package]
name = "scc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
redscript = { path = "../core" }
redscript-compiler = { path = "../compiler" }
log.workspace = true
byteorder.workspace = true
thiserror.workspace = true
flexi_logger.workspace = true
hashbrown = { workspace = true, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
toml = "0.7"
vmap = { version = "0.5", default-features = false, optional = true }
fd-lock = "3"
msgbox = { version = "0.7", optional = true }

[features]
popup = ["msgbox"]
mmap = ["vmap"]
