[package]
name = "scc"
version = "0.3.3-dev"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[dependencies]
redscript = { path = "../core" }
redscript-compiler = { path = "../compiler" }
byteorder = "1.4"
vmap = { version = "0.4", default-features = false }
log = "0.4"
fern = "0.6"
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
fd-lock = "3.0"
msgbox = "0.6"

[package.metadata.release]
disable-tag = true
