[package]
name = "scc"
version = "0.3.2"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[dependencies]
redscript = { path = "../core" }
redscript-compiler = { path = "../compiler" }
byteorder = "1.4"
log = "0.4"
simplelog = { version = "0.10", default_features = false }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
fd-lock = "3.0"
msgbox = "0.6"

[package.metadata.release]
disable-tag = true
