[package]
name = "redscript-cli"
version = "0.3.5-dev"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[dependencies]
redscript = { path = "../core" }
redscript-decompiler = { path = "../decompiler" }
redscript-compiler = { path = "../compiler" }
vmap = { version = "0.4", default-features = false }
gumdrop = "0.8"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }

[package.metadata.release]
tag = false
