[package]
name = "redscript-cli"
version = "0.3.0"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[dependencies]
redscript = { path = "../core" }
redscript-decompiler = { path = "../decompiler" }
redscript-compiler = { path = "../compiler" }
gumdrop = "0.8"
log = "0.4"
simplelog = "0.10"

[package.metadata.release]
disable-tag = true
