[package]
name = "redscript-compiler"
version = "0.3.0-RC3"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
redscript = { path = "../core" }
peg = "0.7"
hamt-sync = "0.2"
sequence_trie = "0.3"
strum = { version = "0.21", features = ["derive"] }
walkdir = "2"
log = "0.4"

[package.metadata.release]
disable-tag = true
