[package]
name = "scc-lib-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dev-dependencies]
minidl = "0.1"
pretty_assertions = "1"
assert_fs = "1"

[build-dependencies]
bindgen = "0.69"

[lints]
workspace = true
